import nodemailer from 'nodemailer';
import fs from 'fs';
import dotenv from 'dotenv';
dotenv.config();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

const attachment = fs.readFileSync('/home/ubuntu/CPI_Demand_Report.xlsx');
const now = new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' });

await transporter.sendMail({
  from: `"MatchPro™ Intelligence" <${process.env.REPORT_FROM_EMAIL}>`,
  to: 'momenmaisara@crystalpowerinvestments.com, maisaramoamen@gmail.com',
  subject: `MatchPro™ Demand Report — Privado | Madinaty Villas | Rehab Villas — ${now}`,
  html: `
    <div style="font-family:Calibri,Arial,sans-serif;max-width:680px;margin:0 auto;">
      <div style="background:#0D1B2A;padding:28px 32px;border-radius:8px 8px 0 0;">
        <h1 style="color:#C9A84C;margin:0;font-size:22px;letter-spacing:1px;">MatchPro™ Demand Intelligence</h1>
        <p style="color:#F5E6C0;margin:6px 0 0;font-size:13px;">Crystal Power Investments — ${now}</p>
      </div>
      <div style="background:#F9F9F9;padding:28px 32px;border:1px solid #E0E0E0;">
        <p style="color:#1A1A2E;font-size:14px;margin:0 0 18px;">Please find attached the targeted demand intelligence report with <strong>202 unique verified leads</strong> across 3 sheets:</p>
        <table style="width:100%;border-collapse:collapse;font-size:13px;">
          <tr style="background:#0D1B2A;color:#C9A84C;">
            <th style="padding:10px 14px;text-align:left;border-radius:4px 0 0 0;">Sheet</th>
            <th style="padding:10px 14px;text-align:center;">Records</th>
            <th style="padding:10px 14px;text-align:left;border-radius:0 4px 0 0;">Description</th>
          </tr>
          <tr style="background:#fff;">
            <td style="padding:10px 14px;color:#1A1A2E;font-weight:bold;">🏡 Privado Demand</td>
            <td style="padding:10px 14px;text-align:center;color:#C9A84C;font-weight:bold;">100</td>
            <td style="padding:10px 14px;color:#444;">Buyers & renters looking in Privado compound</td>
          </tr>
          <tr style="background:#EEF2F7;">
            <td style="padding:10px 14px;color:#1A1A2E;font-weight:bold;">🌿 Madinaty Villa Demand</td>
            <td style="padding:10px 14px;text-align:center;color:#C9A84C;font-weight:bold;">64</td>
            <td style="padding:10px 14px;color:#444;">Buyers seeking villas, townhouses, twin houses in Madinaty</td>
          </tr>
          <tr style="background:#fff;">
            <td style="padding:10px 14px;color:#1A1A2E;font-weight:bold;">🏘 Rehab Villa Demand</td>
            <td style="padding:10px 14px;text-align:center;color:#C9A84C;font-weight:bold;">38</td>
            <td style="padding:10px 14px;color:#444;">Buyers seeking villas & townhouses in الرحاب</td>
          </tr>
          <tr style="background:#0D1B2A;">
            <td style="padding:10px 14px;color:#C9A84C;font-weight:bold;">TOTAL</td>
            <td style="padding:10px 14px;text-align:center;color:#C9A84C;font-weight:bold;">202</td>
            <td style="padding:10px 14px;color:#F5E6C0;">Unique leads, deduplicated, sorted newest first</td>
          </tr>
        </table>
        <div style="margin-top:22px;padding:14px 18px;background:#FFF8E7;border-left:4px solid #C9A84C;border-radius:4px;">
          <p style="margin:0;font-size:12px;color:#555;"><strong>Each record includes:</strong> Primary contact phone · All phones found in message · Contact name · Property type · Location · Budget range · Size range · Bedrooms/Bathrooms · Buyer tier & intent score · Message classification (Demand/Supply/Mixed) · Source WhatsApp group · Full original message text</p>
        </div>
        <p style="margin-top:22px;font-size:12px;color:#888;font-style:italic;">Generated by MatchPro™ WhatsApp Intelligence Platform · Crystal Power Investments · CONFIDENTIAL</p>
      </div>
    </div>
  `,
  attachments: [{
    filename: `CPI_Demand_Report_${new Date().toISOString().slice(0,10)}.xlsx`,
    content: attachment,
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  }],
});

console.log('✅ Email sent successfully');
