import nodemailer from 'nodemailer';
import fs from 'fs';
import dotenv from 'dotenv';
dotenv.config();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false,
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
});

const attachment = fs.readFileSync('/home/ubuntu/CPI_5Sheet_Demand_Report.xlsx');
const now = new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' });

const rows = [
  ['🏡 Privado Studio + Garden', 3,  'Renters looking for studio with garden/terrace in Privado'],
  ['🏢 B7 Studio Rentals',       11, 'Renters looking for studios in B7 block'],
  ['💼 Privado Apt Buyers',      49, 'Buyers looking to purchase apartments in Privado (for your sale)'],
  ['🌙 Dreamland Renters',        2, 'People looking to rent in Dreamland'],
  ['🌿 Madinaty Villa Today',     8, 'Villa/townhouse demand in Madinaty — today & yesterday only'],
];

const tableRows = rows.map(([name, count, desc], i) =>
  `<tr style="background:${i%2===0?'#fff':'#EEF2F7'}">
    <td style="padding:10px 14px;font-weight:bold;color:#1A1A2E;">${name}</td>
    <td style="padding:10px 14px;text-align:center;color:#C9A84C;font-weight:bold;">${count}</td>
    <td style="padding:10px 14px;color:#444;">${desc}</td>
  </tr>`
).join('');

await transporter.sendMail({
  from: `"MatchPro™ Intelligence" <${process.env.REPORT_FROM_EMAIL}>`,
  to: 'momenmaisara@crystalpowerinvestments.com, maisaramoamen@gmail.com',
  subject: `MatchPro™ Targeted Demand — Privado | B7 | Dreamland | Madinaty Villas — ${now}`,
  html: `
    <div style="font-family:Calibri,Arial,sans-serif;max-width:680px;margin:0 auto;">
      <div style="background:#0D1B2A;padding:28px 32px;border-radius:8px 8px 0 0;">
        <h1 style="color:#C9A84C;margin:0;font-size:22px;">MatchPro™ Targeted Demand Report</h1>
        <p style="color:#F5E6C0;margin:6px 0 0;font-size:13px;">Crystal Power Investments — ${now}</p>
      </div>
      <div style="background:#F9F9F9;padding:28px 32px;border:1px solid #E0E0E0;">
        <p style="color:#1A1A2E;font-size:14px;margin:0 0 18px;">Attached: <strong>73 unique verified demand leads</strong> across 5 targeted sheets:</p>
        <table style="width:100%;border-collapse:collapse;font-size:13px;">
          <tr style="background:#0D1B2A;color:#C9A84C;">
            <th style="padding:10px 14px;text-align:left;">Sheet</th>
            <th style="padding:10px 14px;text-align:center;">Records</th>
            <th style="padding:10px 14px;text-align:left;">Description</th>
          </tr>
          ${tableRows}
          <tr style="background:#0D1B2A;">
            <td style="padding:10px 14px;color:#C9A84C;font-weight:bold;">TOTAL</td>
            <td style="padding:10px 14px;text-align:center;color:#C9A84C;font-weight:bold;">73</td>
            <td style="padding:10px 14px;color:#F5E6C0;">Unique leads, deduplicated, newest first</td>
          </tr>
        </table>
        <div style="margin-top:20px;padding:14px 18px;background:#FFF8E7;border-left:4px solid #C9A84C;border-radius:4px;">
          <p style="margin:0;font-size:12px;color:#555;"><strong>Each record includes:</strong> Primary phone · All phones in message · Contact name · Property type · Location · Budget range · Size range · Bedrooms/Bathrooms · Garden/outdoor indicator · Buyer tier · Intent score · Message classification · Source WhatsApp group · Full original message text</p>
        </div>
        <p style="margin-top:20px;font-size:11px;color:#888;font-style:italic;">Generated by MatchPro™ · Crystal Power Investments · CONFIDENTIAL</p>
      </div>
    </div>
  `,
  attachments: [{
    filename: `CPI_Targeted_Demand_${new Date().toISOString().slice(0,10)}.xlsx`,
    content: attachment,
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  }],
});

console.log('✅ Email sent');
