import nodemailer from 'nodemailer';
import fs from 'fs';
import dotenv from 'dotenv';
dotenv.config();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false,
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
});

await transporter.verify();
console.log('[Email] SMTP verified ✅');

const info = await transporter.sendMail({
  from: `"MatchPro™ Intelligence" <${process.env.SMTP_USER}>`,
  to: process.env.REPORT_TO_EMAIL || 'momenmaisara@crystalpowerinvestments.com',
  subject: '📊 Properties Under EGP 3M — Investment Intelligence Report | CPI',
  html: `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#0D1B2A;padding:20px;text-align:center">
        <h2 style="color:#C9A84C;margin:0">CRYSTAL POWER INVESTMENTS</h2>
        <p style="color:#F5E6C0;margin:5px 0">MatchPro™ Intelligence Report</p>
      </div>
      <div style="padding:20px;background:#f9f9f9">
        <h3 style="color:#0D1B2A">Properties Under EGP 3,000,000 — Investment Report</h3>
        <p>Dear M,</p>
        <p>Please find attached the comprehensive investment intelligence report covering <strong>235 active listings</strong> under EGP 3,000,000 in Madinaty and New Cairo.</p>
        <table style="width:100%;border-collapse:collapse;margin:15px 0">
          <tr style="background:#0D1B2A;color:white">
            <td style="padding:8px;font-weight:bold">Metric</td>
            <td style="padding:8px;font-weight:bold">Value</td>
          </tr>
          <tr style="background:#F5E6C0">
            <td style="padding:8px">Active Listings Under EGP 3M</td>
            <td style="padding:8px"><strong>235</strong></td>
          </tr>
          <tr>
            <td style="padding:8px">Average Asking Price</td>
            <td style="padding:8px">EGP 1,986,667</td>
          </tr>
          <tr style="background:#F5E6C0">
            <td style="padding:8px">Avg Price/m² (vs EGP 38K market)</td>
            <td style="padding:8px"><strong>EGP 21,500/m² (43% below market)</strong></td>
          </tr>
          <tr>
            <td style="padding:8px">Estimated Rental Yield</td>
            <td style="padding:8px" style="color:#1A7A4A"><strong>12–22%/yr</strong></td>
          </tr>
        </table>
        <p><strong>Top Recommendation:</strong> Madinaty B14 Group 143 — 115m², 3BR/2Bath, EGP 2.2M total, EGP 350K offer, 14.4% rental yield. Contact: 01060000421</p>
        <p style="color:#666;font-size:12px">Generated by MatchPro™ Intelligence System | Crystal Power Investments | ${new Date().toLocaleDateString('en-GB', {day:'2-digit',month:'long',year:'numeric'})}</p>
      </div>
    </div>
  `,
  attachments: [{
    filename: 'CPI_Under3M_Investment_Report.pdf',
    path: '/home/ubuntu/CPI_Under3M_Investment_Report.pdf',
    contentType: 'application/pdf'
  }]
});

console.log('[Email] ✅ Report sent!');
console.log('[Email] Message ID:', info.messageId);
console.log('[Email] Recipient:', process.env.REPORT_TO_EMAIL);
