/**
 * Send Report via Email
 * Sends the generated Excel report to the owner
 */

import nodemailer from 'nodemailer';
import * as fs from 'fs';

export async function sendReportEmail(filename: string, recipientEmail: string): Promise<boolean> {
  try {
    // Verify file exists
    if (!fs.existsSync(filename)) {
      console.error(`❌ File not found: ${filename}`);
      return false;
    }

    // Get SMTP config from environment
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = process.env.SMTP_PORT || '587';
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const fromEmail = process.env.REPORT_FROM_EMAIL || smtpUser;

    if (!smtpHost || !smtpUser || !smtpPass) {
      console.warn('⚠️ SMTP credentials not configured, skipping email');
      return false;
    }

    // Create transporter
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: parseInt(smtpPort),
      secure: smtpPort === '465',
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    // Read file
    const fileContent = fs.readFileSync(filename);
    const fileName = filename.split('/').pop() || 'MatchPro_Report.xlsx';

    // Send email
    const info = await transporter.sendMail({
      from: fromEmail,
      to: recipientEmail,
      subject: `MatchPro Real Estate Report - ${new Date().toLocaleDateString('en-US')}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #333;">📊 MatchPro Real Estate Report</h2>
          
          <p>Dear Owner,</p>
          
          <p>Your automated MatchPro report has been generated successfully.</p>
          
          <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Report Summary:</h3>
            <ul>
              <li><strong>Report Type:</strong> Demand Analysis</li>
              <li><strong>Generated:</strong> ${new Date().toLocaleString()}</li>
              <li><strong>File:</strong> ${fileName}</li>
              <li><strong>Sheets:</strong> 21 (All_Demands + Area-specific + Summary)</li>
            </ul>
          </div>
          
          <h3>📋 What's Inside:</h3>
          <ul>
            <li><strong>All_Demands:</strong> Complete list of all demand messages</li>
            <li><strong>Area Sheets:</strong> Demands segregated by location</li>
            <li><strong>Summary:</strong> Analysis and statistics</li>
            <li><strong>Arabic Sheets:</strong> Localized area reports</li>
          </ul>
          
          <p style="color: #666; font-size: 12px; margin-top: 30px;">
            This is an automated report generated by MatchPro System.<br>
            Next report will be generated in 6 hours.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: fileName,
          content: fileContent,
        },
      ],
    });

    console.log(`✅ Email sent successfully: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error('❌ Failed to send email:', error);
    return false;
  }
}
